### ISSUE TITLE
Issues with Cyrillic characters.

### ISSUE THREAD

**Issue by jefflembeck** [filamentgroup/grumpicon#19]
See: http://jlembeck-monosnap.s3.amazonaws.com/cyrillic.svg

Originally reported: https://github.com/filamentgroup/grunticon/issues/52

**Comment by efender** [comment]
As I see you apply charset US-ASCII, why not utf-8 ?
I converted this svg by my scss mixin:
```scss

@function str-replace($string, $search, $replace: '') {
    $index: str-index($string, $search);

    @if $index {
        @return str-slice($string, 1, $index - 1) + $replace + str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
    }

    @return $string;
}

@mixin my-base64-svg($file) {
    $file: '#{$file}.svg';
    $base64-file: inline_image($file);
    background-image: str-replace($base64-file, 'data:image/svg+xml;base64', 'data:image/svg+xml;charset=utf-8;base64');
}

.svg {
    @include my-base64-svg('svg/cyrillic');
}
```
And I got the correct result:
```css
.svg {
background-image: url('data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI2NTAiIGhlaWdodD0iMzQ3LjA3OCIgZm9udC1zaXplPSIxNSIgZm9udC1mYW1pbHk9IlZlcmRhbmEsIEhlbHZldGljYSwgc2Fucy1zZXJpZiI+PGRlZnM+PHBhdHRlcm4gaWQ9ImEiIHBhdHRlcm5Vbml0cz0idXNlclNwYWNlT25Vc2UiIHdpZHRoPSI3IiBoZWlnaHQ9IjciPjxwYXRoIGQ9Ik0wIDdsNy03IiBmaWxsPSJub25lIiBzdHJva2U9IiNlOGU5ZWEiLz48L3BhdHRlcm4+PC9kZWZzPjxwYXRoIGZpbGw9InVybCgjYSkiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAgMikiIGQ9Ik0wIDBoNjUwdjI2NkgweiIvPjxnIGNsYXNzPSJmaWVsZCI+PHRleHQgZmlsbD0iIzI4NGI4MSIgZm9udC13ZWlnaHQ9ImJvbGQiIGZvbnQtc2l6ZT0iLjhlbSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjUgMjApIj48dHNwYW4gZHk9IjAiIHg9IjAiPtCU0LjQvdCw0LzQuNC60LAg0L7QsdGK0ZHQvNC+0LIg0YLQtdGF0L3QvtC70L7Qs9C40YfQtdGB0LrQvtCz0L4g0L/RgNC40YHQvtC10LTQuNC90LXQvdC40Y8gPC90c3Bhbj48dHNwYW4gZHk9IjEuNWVtIiB4PSIwIj7Qs9C10L3QtdGA0LjRgNGD0Y7RidC40YUg0Y3QvdC10YDQs9C+0YPRgdGC0LDQvdC+0LLQvtC6INC30LDRj9Cy0LjRgtC10LvQtdC5INCy0YHQtdCz0L4g0L/QviDQntCx0YnQtdGB0YLQstGDLCDQnNCS0YI8L3RzcGFuPjwvdGV4dD48ZyBjbGFzcz0iZ3JhcGgtYXJlYSI+PGcgY2xhc3M9InkgYXhpcyIgZmlsbD0iIzI4NGI4MSIgZm9udC1zaXplPSIuOGVtIj48dGV4dCBjbGFzcz0idGljayIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjUgMjIxLjgpIiBkb21pbmFudC1iYXNlbGluZT0iY2VudHJhbCI+MjAxMDwvdGV4dD48dGV4dCBjbGFzcz0idGljayIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjUgMTUxLjMwNSkiIGRvbWluYW50LWJhc2VsaW5lPSJjZW50cmFsIj4yMDExPC90ZXh0Pjx0ZXh0IGNsYXNzPSJ0aWNrIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgyNSA4MC44MDgpIiBkb21pbmFudC1iYXNlbGluZT0iY2VudHJhbCI+MjAxMjwvdGV4dD48L2c+PGcgY2xhc3M9ImxheWVyLTAgbGF5ZXIiIGZpbGw9IiMyODRiODEiIHN0cm9rZT0iIzI4NGI4MSI+PHBhdGggc3Ryb2tlPSJub25lIiBkPSJNODIgMTkzLjYwM2g0NjcuMTU4djE3LjhIODJ6TTgyIDEyMy4xMDZoNDY4djE3LjhIODJ6TTgyIDUyLjYxaDc1LjM2OHYxNy43OThIODJ6Ii8+PHRleHQgY2xhc3M9ImxhYmVsIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSg1NTQuMTU4IDIwMy4wMDIpIiBzdHJva2Utd2lkdGg9IjAiIGZvbnQtc2l6ZT0iLjY2N2VtIiBmaWxsPSIjMzY4Y2M1IiBkb21pbmFudC1iYXNlbGluZT0iY2VudHJhbCI+MjIxLjk8L3RleHQ+PHRleHQgY2xhc3M9ImxhYmVsIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSg1NTUgMTMyLjUwNikiIHN0cm9rZS13aWR0aD0iMCIgZm9udC1zaXplPSIuNjY3ZW0iIGZpbGw9IiMzNjhjYzUiIGRvbWluYW50LWJhc2VsaW5lPSJjZW50cmFsIj4yMjIuMzwvdGV4dD48dGV4dCBjbGFzcz0ibGFiZWwiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDE2Mi4zNjggNjIuMDEpIiBzdHJva2Utd2lkdGg9IjAiIGZvbnQtc2l6ZT0iLjY2N2VtIiBmaWxsPSIjMzY4Y2M1IiBkb21pbmFudC1iYXNlbGluZT0iY2VudHJhbCI+MzUuODwvdGV4dD48L2c+PGcgY2xhc3M9ImxheWVyLTEgbGF5ZXIiIGZpbGw9IiNjMTlhNTkiIHN0cm9rZT0iI2MxOWE1OSI+PHBhdGggc3Ryb2tlPSJub25lIiBkPSJNODIgMjEyLjQwMmg0MDcuNTh2MTcuOEg4MnpNODIgMTQxLjkwNWgzNy44OTV2MTcuOEg4MnoiLz48dGV4dCBjbGFzcz0ibGFiZWwiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDQ5NC41OCAyMjEuOCkiIHN0cm9rZS13aWR0aD0iMCIgZm9udC1zaXplPSIuNjY3ZW0iIGZpbGw9IiMzNjhjYzUiIGRvbWluYW50LWJhc2VsaW5lPSJjZW50cmFsIj4xOTMuNjwvdGV4dD48dGV4dCBjbGFzcz0ibGFiZWwiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDEyNC44OTUgMTUxLjMwNSkiIHN0cm9rZS13aWR0aD0iMCIgZm9udC1zaXplPSIuNjY3ZW0iIGZpbGw9IiMzNjhjYzUiIGRvbWluYW50LWJhc2VsaW5lPSJjZW50cmFsIj4xOC4wPC90ZXh0Pjx0ZXh0IGNsYXNzPSJsYWJlbCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoODcgODAuODA4KSIgc3Ryb2tlLXdpZHRoPSIwIiBmb250LXNpemU9Ii42NjdlbSIgZmlsbD0iIzM2OGNjNSIgZG9taW5hbnQtYmFzZWxpbmU9ImNlbnRyYWwiPjAuMDwvdGV4dD48L2c+PGcgY2xhc3M9ImxheWVyLTIgbGF5ZXIiIGZpbGw9IiMzZTZjYjEiIHN0cm9rZT0iIzNlNmNiMSI+PHBhdGggc3Ryb2tlPSJub25lIiBkPSJNODIgMjMxLjJoODQuMjFWMjQ5SDgyek04MiA5MC4yMDhoMjMxLjU4djE3LjhIODJ6Ii8+PHRleHQgY2xhc3M9ImxhYmVsIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxNzEuMjEgMjQwLjYpIiBzdHJva2Utd2lkdGg9IjAiIGZvbnQtc2l6ZT0iLjY2N2VtIiBmaWxsPSIjMzY4Y2M1IiBkb21pbmFudC1iYXNlbGluZT0iY2VudHJhbCI+NDAuMDwvdGV4dD48dGV4dCBjbGFzcz0ibGFiZWwiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDg3IDE3MC4xMDQpIiBzdHJva2Utd2lkdGg9IjAiIGZvbnQtc2l6ZT0iLjY2N2VtIiBmaWxsPSIjMzY4Y2M1IiBkb21pbmFudC1iYXNlbGluZT0iY2VudHJhbCI+MC4wPC90ZXh0Pjx0ZXh0IGNsYXNzPSJsYWJlbCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMzE4LjU4IDk5LjYwNykiIHN0cm9rZS13aWR0aD0iMCIgZm9udC1zaXplPSIuNjY3ZW0iIGZpbGw9IiMzNjhjYzUiIGRvbWluYW50LWJhc2VsaW5lPSJjZW50cmFsIj4xMTAuMDwvdGV4dD48L2c+PC9nPjxnIGNsYXNzPSJsZWdlbmQiIGZvbnQtc2l6ZT0iLjczM2VtIj48ZyBjbGFzcz0ibGVnZW5kLWl0ZW0iIGZpbGw9IiMyODRiODEiPjxwYXRoIGQ9Ik0wIDI5MGgxNXYxNUgweiIvPjx0ZXh0IGR5PSI3LjUiIGZvbnQtc2l6ZT0iMS4wOTFlbSIgZHg9IjIyLjUiIGRvbWluYW50LWJhc2VsaW5lPSJjZW50cmFsIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDI5MCkiPtCe0LHRitC10Lwg0L/QvtC00LDQvdC90YvRhSDQt9Cw0Y/QstC+0Log0L3QsCDQotCfPC90ZXh0PjwvZz48ZyBjbGFzcz0ibGVnZW5kLWl0ZW0iPjxwYXRoIGZpbGw9IiNjMTlhNTkiIGQ9Ik0yMjkgMjkwaDE1djE1aC0xNXoiLz48dGV4dCBmaWxsPSIjMjg0YjgxIiBkeT0iNy41IiBmb250LXNpemU9IjEuMDkxZW0iIGR4PSIyMi41IiBkb21pbmFudC1iYXNlbGluZT0iY2VudHJhbCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjI5IDI5MCkiPtCe0LHRitC10Lwg0LfQsNC60LvRjtGH0LXQvdC90YvRhSDQtNC+0LPQvtCy0L7RgNC+0LIg0L3QsCDQotCfPC90ZXh0PjwvZz48ZyBjbGFzcz0ibGVnZW5kLWl0ZW0iPjxwYXRoIGZpbGw9IiMzZTZjYjEiIGQ9Ik0wIDMyMGgxNXYxNUgweiIvPjx0ZXh0IGZpbGw9IiMyODRiODEiIGR5PSI3LjUiIGZvbnQtc2l6ZT0iMS4wOTFlbSIgZHg9IjIyLjUiIGRvbWluYW50LWJhc2VsaW5lPSJjZW50cmFsIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwIDMyMCkiPtCe0LHRitC10Lwg0LjRgdC/0L7Qu9C90LXQvdC90YvRhSDQtNC+0LPQvtCy0L7RgNC+0LIg0KLQnzwvdGV4dD48L2c+PC9nPjwvZz48cGF0aCBkPSJNMCAyNzBoNjUwTTAgMGg2NTAiIHN0cm9rZT0iI2RlZGZlMCIvPjwvc3ZnPg==');
}
```
![1434256627073](https://cloud.githubusercontent.com/assets/6908417/8147116/54d27944-1268-11e5-9ca7-beea61010aa9.png)

**Comment by johnbender** [comment]
@efender 

I'm new to this issue but I think the original was Cyrillic characters in the original SVG input and not in the base64 encoded string (which I think is what you're suggesting)? 

I'll check with @jefflembeck when I can.

**Comment by efender** [comment]
Oh, I see you are not using the encoding base64.
But maybe if you change the encoding to utf-8 will be closed this issue.

**Comment by jefflembeck** [comment]
@efender @johnbender we use ascii instead of utf-8 because that is what the spec for SVG calls for, see:

https://github.com/filamentgroup/directory-encoder/issues/18#issuecomment-70879036

We inline the svg instead of base64 for two reasons:

1. Size. base64 immediately bloats the file
2. Compression. The produced css file for SVG, when run through gzip, is immensely smaller than the original file. This gain is not reproducible with base64.

**Comment by scottjehl** [comment]
Also worth adding that not using base64 allows us to provide the embed feature for inline SVG, since we pull the markup directly from the CSS declarations when embedding.

**Comment by efender** [comment]
I see. Thanks!

**Comment by efender** [comment]
Thanks again. 
I decided to find out more about embed method and I found the article with a more efficient solution http://codepen.io/Tigt/blog/optimizing-svgs-in-data-uris - author offers only encode special characters.

Result for cyrillic.svg (plain / gzipped):
grumpicon - 9 654 bytes / 1 625 bytes
mixed method - 6 775 bytes / 1 547 bytes

**Grumpicon CSS**
```css
.icon-cyrillic {
	background-image: url('data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%20version%3D%221.1%22%20xmlns%3Axlink%3D%22http%3A//www.w3.org/1999/xlink%22%20width%3D%22650%22%20height%3D%22347.078125%22%20style%3D%22font-size%3A%2015px%3B%20font-family%3A%20Verdana%2C%20Helvetica%2C%20sans-serif%3B%20font-style%3A%20normal%3B%22%3E%3Cdefs%3E%3Cpattern%20id%3D%22bg-45deg%23dynamics-technological-connection-power-plants-generating-MW-rus-sp%22%20patternUnits%3D%22userSpaceOnUse%22%20width%3D%227%22%20height%3D%227%22%3E%3Cpath%20d%3D%22M0%2C7%20L7%2C0%22%20fill%3D%22none%22%20stroke-width%3D%221%22%20stroke%3D%22%23e8e9ea%22%3E%3C/path%3E%3C/pattern%3E%3C/defs%3E%3Crect%20width%3D%22650%22%20height%3D%22266%22%20fill%3D%22url%28%23bg-45deg%23dynamics-technological-connection-power-plants-generating-MW-rus-sp%29%22%20transform%3D%22translate%280%2C%202%29%22%3E%3C/rect%3E%3Cg%20class%3D%22field%22%20transform%3D%22translate%2825%2C20%29%22%3E%3Ctext%20fill%3D%22%23284b81%22%20font-weight%3D%22bold%22%20font-size%3D%220.8em%22%3E%3Ctspan%20dy%3D%220%22%20x%3D%220%22%3E%u0414%u0438%u043D%u0430%u043C%u0438%u043A%u0430%20%u043E%u0431%u044A%u0451%u043C%u043E%u0432%20%u0442%u0435%u0445%u043D%u043E%u043B%u043E%u0433%u0438%u0447%u0435%u0441%u043A%u043E%u0433%u043E%20%u043F%u0440%u0438%u0441%u043E%u0435%u0434%u0438%u043D%u0435%u043D%u0438%u044F%20%3C/tspan%3E%3Ctspan%20dy%3D%221.5em%22%20x%3D%220%22%3E%u0433%u0435%u043D%u0435%u0440%u0438%u0440%u0443%u044E%u0449%u0438%u0445%20%u044D%u043D%u0435%u0440%u0433%u043E%u0443%u0441%u0442%u0430%u043D%u043E%u0432%u043E%u043A%20%u0437%u0430%u044F%u0432%u0438%u0442%u0435%u043B%u0435%u0439%20%u0432%u0441%u0435%u0433%u043E%20%u043F%u043E%20%u041E%u0431%u0449%u0435%u0441%u0442%u0432%u0443%2C%20%u041C%u0412%u0442%3C/tspan%3E%3C/text%3E%3Cg%20class%3D%22graph-area%22%20transform%3D%22translate%280%2C32.609375%29%22%3E%3Cg%20class%3D%22y%20axis%22%3E%3Ctext%20class%3D%22tick%22%20transform%3D%22translate%280%2C169.1919642857143%29%22%20fill%3D%22%23284b81%22%20style%3D%22font-size%3A%200.8em%3B%20dominant-baseline%3A%20central%3B%22%3E2010%3C/text%3E%3Ctext%20class%3D%22tick%22%20transform%3D%22translate%280%2C98.69531250000001%29%22%20fill%3D%22%23284b81%22%20style%3D%22font-size%3A%200.8em%3B%20dominant-baseline%3A%20central%3B%22%3E2011%3C/text%3E%3Ctext%20class%3D%22tick%22%20transform%3D%22translate%280%2C28.19866071428572%29%22%20fill%3D%22%23284b81%22%20style%3D%22font-size%3A%200.8em%3B%20dominant-baseline%3A%20central%3B%22%3E2012%3C/text%3E%3C/g%3E%3Cg%20class%3D%22layer-0%20layer%22%20fill%3D%22%23284b81%22%20stroke%3D%22%23284b81%22%20transform%3D%22translate%2857%2C0%29%22%3E%3Crect%20height%3D%2217.799107142857146%22%20width%3D%22467.1578947368421%22%20transform%3D%22translate%280%2C%20140.99330357142858%29%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Crect%20height%3D%2217.799107142857146%22%20width%3D%22468%22%20transform%3D%22translate%280%2C%2070.49665178571429%29%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Crect%20height%3D%2217.799107142857146%22%20width%3D%2275.36842105263158%22%20transform%3D%22translate%280%2C%200%29%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Ctext%20class%3D%22label%22%20transform%3D%22translate%28472.1578947368421%2C%20150.39285714285717%29%22%20stroke-width%3D%220%22%20font-size%3D%220.6666666666666666em%22%20text-anchor%3D%22start%22%20fill%3D%22%23368cc5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E221.9%3C/text%3E%3Ctext%20class%3D%22label%22%20transform%3D%22translate%28473%2C%2079.89620535714286%29%22%20stroke-width%3D%220%22%20font-size%3D%220.6666666666666666em%22%20text-anchor%3D%22start%22%20fill%3D%22%23368cc5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E222.3%3C/text%3E%3Ctext%20class%3D%22label%22%20transform%3D%22translate%2880.36842105263158%2C%209.399553571428573%29%22%20stroke-width%3D%220%22%20font-size%3D%220.6666666666666666em%22%20text-anchor%3D%22start%22%20fill%3D%22%23368cc5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E35.8%3C/text%3E%3C/g%3E%3Cg%20class%3D%22layer-1%20layer%22%20fill%3D%22%23c19a59%22%20stroke%3D%22%23c19a59%22%20transform%3D%22translate%2857%2C0%29%22%3E%3Crect%20height%3D%2217.799107142857146%22%20width%3D%22407.57894736842104%22%20transform%3D%22translate%280%2C%20159.79241071428572%29%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Crect%20height%3D%2217.799107142857146%22%20width%3D%2237.89473684210526%22%20transform%3D%22translate%280%2C%2089.29575892857144%29%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Crect%20height%3D%2217.799107142857146%22%20width%3D%220%22%20transform%3D%22translate%280%2C%2018.799107142857146%29%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Ctext%20class%3D%22label%22%20transform%3D%22translate%28412.57894736842104%2C%20169.1919642857143%29%22%20stroke-width%3D%220%22%20font-size%3D%220.6666666666666666em%22%20text-anchor%3D%22start%22%20fill%3D%22%23368cc5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E193.6%3C/text%3E%3Ctext%20class%3D%22label%22%20transform%3D%22translate%2842.89473684210526%2C%2098.69531250000001%29%22%20stroke-width%3D%220%22%20font-size%3D%220.6666666666666666em%22%20text-anchor%3D%22start%22%20fill%3D%22%23368cc5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E18.0%3C/text%3E%3Ctext%20class%3D%22label%22%20transform%3D%22translate%285%2C%2028.19866071428572%29%22%20stroke-width%3D%220%22%20font-size%3D%220.6666666666666666em%22%20text-anchor%3D%22start%22%20fill%3D%22%23368cc5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E0.0%3C/text%3E%3C/g%3E%3Cg%20class%3D%22layer-2%20layer%22%20fill%3D%22%233e6cb1%22%20stroke%3D%22%233e6cb1%22%20transform%3D%22translate%2857%2C0%29%22%3E%3Crect%20height%3D%2217.799107142857146%22%20width%3D%2284.21052631578948%22%20transform%3D%22translate%280%2C%20178.5915178571429%29%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Crect%20height%3D%2217.799107142857146%22%20width%3D%220%22%20transform%3D%22translate%280%2C%20108.09486607142858%29%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Crect%20height%3D%2217.799107142857146%22%20width%3D%22231.57894736842107%22%20transform%3D%22translate%280%2C%2037.59821428571429%29%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Ctext%20class%3D%22label%22%20transform%3D%22translate%2889.21052631578948%2C%20187.99107142857147%29%22%20stroke-width%3D%220%22%20font-size%3D%220.6666666666666666em%22%20text-anchor%3D%22start%22%20fill%3D%22%23368cc5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E40.0%3C/text%3E%3Ctext%20class%3D%22label%22%20transform%3D%22translate%285%2C%20117.49441964285715%29%22%20stroke-width%3D%220%22%20font-size%3D%220.6666666666666666em%22%20text-anchor%3D%22start%22%20fill%3D%22%23368cc5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E0.0%3C/text%3E%3Ctext%20class%3D%22label%22%20transform%3D%22translate%28236.57894736842107%2C%2046.99776785714286%29%22%20stroke-width%3D%220%22%20font-size%3D%220.6666666666666666em%22%20text-anchor%3D%22start%22%20fill%3D%22%23368cc5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E110.0%3C/text%3E%3C/g%3E%3C/g%3E%3Cg%20class%3D%22legend%22%20transform%3D%22translate%28-25%2C270%29%22%20font-size%3D%220.7333333333333333em%22%20height%3D%2215%22%3E%3Cg%20class%3D%22legend-item%22%20height%3D%2215%22%20transform%3D%22translate%280%2C0%29%22%3E%3Crect%20width%3D%2215%22%20height%3D%2215%22%20fill%3D%22%23284b81%22%20stroke%3D%22%23284b81%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Ctext%20fill%3D%22%23284b81%22%20dy%3D%227.5%22%20font-size%3D%221.0909090909090908em%22%20dx%3D%2222.5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E%u041E%u0431%u044A%u0435%u043C%20%u043F%u043E%u0434%u0430%u043D%u043D%u044B%u0445%20%u0437%u0430%u044F%u0432%u043E%u043A%20%u043D%u0430%20%u0422%u041F%3C/text%3E%3C/g%3E%3Cg%20class%3D%22legend-item%22%20height%3D%2215%22%20transform%3D%22translate%28229%2C0%29%22%3E%3Crect%20width%3D%2215%22%20height%3D%2215%22%20fill%3D%22%23c19a59%22%20stroke%3D%22%23c19a59%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Ctext%20fill%3D%22%23284b81%22%20dy%3D%227.5%22%20font-size%3D%221.0909090909090908em%22%20dx%3D%2222.5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E%u041E%u0431%u044A%u0435%u043C%20%u0437%u0430%u043A%u043B%u044E%u0447%u0435%u043D%u043D%u044B%u0445%20%u0434%u043E%u0433%u043E%u0432%u043E%u0440%u043E%u0432%20%u043D%u0430%20%u0422%u041F%3C/text%3E%3C/g%3E%3Cg%20class%3D%22legend-item%22%20height%3D%2215%22%20transform%3D%22translate%280%2C30%29%22%3E%3Crect%20width%3D%2215%22%20height%3D%2215%22%20fill%3D%22%233e6cb1%22%20stroke%3D%22%233e6cb1%22%20stroke-width%3D%220%22%3E%3C/rect%3E%3Ctext%20fill%3D%22%23284b81%22%20dy%3D%227.5%22%20font-size%3D%221.0909090909090908em%22%20dx%3D%2222.5%22%20style%3D%22dominant-baseline%3A%20central%3B%22%3E%u041E%u0431%u044A%u0435%u043C%20%u0438%u0441%u043F%u043E%u043B%u043D%u0435%u043D%u043D%u044B%u0445%20%u0434%u043E%u0433%u043E%u0432%u043E%u0440%u043E%u0432%20%u0422%u041F%3C/text%3E%3C/g%3E%3C/g%3E%3Cg%20class%3D%22chart-notes%22%20transform%3D%22translate%28-20%2C%20347.078125%29%22%20fill%3D%22%234b4b4b%22%20font-size%3D%220.7333333333333333em%22%3E%3C/g%3E%3Cg%20class%3D%22chart-source%22%20transform%3D%22translate%28-20%2C%20347.078125%29%22%20fill%3D%22%234b4b4b%22%20font-size%3D%220.7333333333333333em%22%3E%3C/g%3E%3C/g%3E%3Cpath%20d%3D%22M0%200%20l650%200%22%20stroke-width%3D%221%22%20stroke%3D%22%23dedfe0%22%20transform%3D%22translate%280%2C%20270%29%22%3E%3C/path%3E%3Cpath%20d%3D%22M0%200%20l650%200%22%20stroke-width%3D%221%22%20stroke%3D%22%23dedfe0%22%3E%3C/path%3E%3C/svg%3E%0A');
	background-repeat: no-repeat;
}
```

**Mixed method CSS**
```css
.icon-cyrillic {
	background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' version='1.1' xmlns:xlink='http://www.w3.org/1999/xlink' width='650' height='347.078125' style='font-size: 15px; font-family: Verdana, Helvetica, sans-serif; font-style: normal;'%3E%3Cdefs%3E%3Cpattern id='bg-45deg%23dynamics-technological-connection-power-plants-generating-MW-rus-sp' patternUnits='userSpaceOnUse' width='7' height='7'%3E%3Cpath d='M0,7 L7,0' fill='none' stroke-width='1' stroke='%23e8e9ea'%3E%3C/path%3E%3C/pattern%3E%3C/defs%3E%3Crect width='650' height='266' fill='url(%23bg-45deg%23dynamics-technological-connection-power-plants-generating-MW-rus-sp)' transform='translate(0, 2)'%3E%3C/rect%3E%3Cg class='field' transform='translate(25,20)'%3E%3Ctext fill='%23284b81' font-weight='bold' font-size='0.8em'%3E%3Ctspan dy='0' x='0'%3EДинамика объёмов технологического присоединения %3C/tspan%3E%3Ctspan dy='1.5em' x='0'%3Eгенерирующих энергоустановок заявителей всего по Обществу, МВт%3C/tspan%3E%3C/text%3E%3Cg class='graph-area' transform='translate(0,32.609375)'%3E%3Cg class='y axis'%3E%3Ctext class='tick' transform='translate(0,169.1919642857143)' fill='%23284b81' style='font-size: 0.8em; dominant-baseline: central;'%3E2010%3C/text%3E%3Ctext class='tick' transform='translate(0,98.69531250000001)' fill='%23284b81' style='font-size: 0.8em; dominant-baseline: central;'%3E2011%3C/text%3E%3Ctext class='tick' transform='translate(0,28.19866071428572)' fill='%23284b81' style='font-size: 0.8em; dominant-baseline: central;'%3E2012%3C/text%3E%3C/g%3E%3Cg class='layer-0 layer' fill='%23284b81' stroke='%23284b81' transform='translate(57,0)'%3E%3Crect height='17.799107142857146' width='467.1578947368421' transform='translate(0, 140.99330357142858)' stroke-width='0'%3E%3C/rect%3E%3Crect height='17.799107142857146' width='468' transform='translate(0, 70.49665178571429)' stroke-width='0'%3E%3C/rect%3E%3Crect height='17.799107142857146' width='75.36842105263158' transform='translate(0, 0)' stroke-width='0'%3E%3C/rect%3E%3Ctext class='label' transform='translate(472.1578947368421, 150.39285714285717)' stroke-width='0' font-size='0.6666666666666666em' text-anchor='start' fill='%23368cc5' style='dominant-baseline: central;'%3E221.9%3C/text%3E%3Ctext class='label' transform='translate(473, 79.89620535714286)' stroke-width='0' font-size='0.6666666666666666em' text-anchor='start' fill='%23368cc5' style='dominant-baseline: central;'%3E222.3%3C/text%3E%3Ctext class='label' transform='translate(80.36842105263158, 9.399553571428573)' stroke-width='0' font-size='0.6666666666666666em' text-anchor='start' fill='%23368cc5' style='dominant-baseline: central;'%3E35.8%3C/text%3E%3C/g%3E%3Cg class='layer-1 layer' fill='%23c19a59' stroke='%23c19a59' transform='translate(57,0)'%3E%3Crect height='17.799107142857146' width='407.57894736842104' transform='translate(0, 159.79241071428572)' stroke-width='0'%3E%3C/rect%3E%3Crect height='17.799107142857146' width='37.89473684210526' transform='translate(0, 89.29575892857144)' stroke-width='0'%3E%3C/rect%3E%3Crect height='17.799107142857146' width='0' transform='translate(0, 18.799107142857146)' stroke-width='0'%3E%3C/rect%3E%3Ctext class='label' transform='translate(412.57894736842104, 169.1919642857143)' stroke-width='0' font-size='0.6666666666666666em' text-anchor='start' fill='%23368cc5' style='dominant-baseline: central;'%3E193.6%3C/text%3E%3Ctext class='label' transform='translate(42.89473684210526, 98.69531250000001)' stroke-width='0' font-size='0.6666666666666666em' text-anchor='start' fill='%23368cc5' style='dominant-baseline: central;'%3E18.0%3C/text%3E%3Ctext class='label' transform='translate(5, 28.19866071428572)' stroke-width='0' font-size='0.6666666666666666em' text-anchor='start' fill='%23368cc5' style='dominant-baseline: central;'%3E0.0%3C/text%3E%3C/g%3E%3Cg class='layer-2 layer' fill='%233e6cb1' stroke='%233e6cb1' transform='translate(57,0)'%3E%3Crect height='17.799107142857146' width='84.21052631578948' transform='translate(0, 178.5915178571429)' stroke-width='0'%3E%3C/rect%3E%3Crect height='17.799107142857146' width='0' transform='translate(0, 108.09486607142858)' stroke-width='0'%3E%3C/rect%3E%3Crect height='17.799107142857146' width='231.57894736842107' transform='translate(0, 37.59821428571429)' stroke-width='0'%3E%3C/rect%3E%3Ctext class='label' transform='translate(89.21052631578948, 187.99107142857147)' stroke-width='0' font-size='0.6666666666666666em' text-anchor='start' fill='%23368cc5' style='dominant-baseline: central;'%3E40.0%3C/text%3E%3Ctext class='label' transform='translate(5, 117.49441964285715)' stroke-width='0' font-size='0.6666666666666666em' text-anchor='start' fill='%23368cc5' style='dominant-baseline: central;'%3E0.0%3C/text%3E%3Ctext class='label' transform='translate(236.57894736842107, 46.99776785714286)' stroke-width='0' font-size='0.6666666666666666em' text-anchor='start' fill='%23368cc5' style='dominant-baseline: central;'%3E110.0%3C/text%3E%3C/g%3E%3C/g%3E%3Cg class='legend' transform='translate(-25,270)' font-size='0.7333333333333333em' height='15'%3E%3Cg class='legend-item' height='15' transform='translate(0,0)'%3E%3Crect width='15' height='15' fill='%23284b81' stroke='%23284b81' stroke-width='0'%3E%3C/rect%3E%3Ctext fill='%23284b81' dy='7.5' font-size='1.0909090909090908em' dx='22.5' style='dominant-baseline: central;'%3EОбъем поданных заявок на ТП%3C/text%3E%3C/g%3E%3Cg class='legend-item' height='15' transform='translate(229,0)'%3E%3Crect width='15' height='15' fill='%23c19a59' stroke='%23c19a59' stroke-width='0'%3E%3C/rect%3E%3Ctext fill='%23284b81' dy='7.5' font-size='1.0909090909090908em' dx='22.5' style='dominant-baseline: central;'%3EОбъем заключенных договоров на ТП%3C/text%3E%3C/g%3E%3Cg class='legend-item' height='15' transform='translate(0,30)'%3E%3Crect width='15' height='15' fill='%233e6cb1' stroke='%233e6cb1' stroke-width='0'%3E%3C/rect%3E%3Ctext fill='%23284b81' dy='7.5' font-size='1.0909090909090908em' dx='22.5' style='dominant-baseline: central;'%3EОбъем исполненных договоров ТП%3C/text%3E%3C/g%3E%3C/g%3E%3Cg class='chart-notes' transform='translate(-20, 347.078125)' fill='%234b4b4b' font-size='0.7333333333333333em'%3E%3C/g%3E%3Cg class='chart-source' transform='translate(-20, 347.078125)' fill='%234b4b4b' font-size='0.7333333333333333em'%3E%3C/g%3E%3C/g%3E%3Cpath d='M0 0 l650 0' stroke-width='1' stroke='%23dedfe0' transform='translate(0, 270)'%3E%3C/path%3E%3Cpath d='M0 0 l650 0' stroke-width='1' stroke='%23dedfe0'%3E%3C/path%3E%3C/svg%3E");
	background-repeat: no-repeat;
}
```

Browser tested - IE9, FF38, Chrome 43, Safari 5.1

The cyrillic characters  are displayed correctly:
![1434399344916](https://cloud.githubusercontent.com/assets/6908417/8169821/ca559c9e-13b4-11e5-9ea0-f18b723e1ab3.png)
